# Generated by Django 3.2.10 on 2023-05-01 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='due_date',
            field=models.DateTimeField(default='2023-04-09T22:58:21.335449Z'),
            preserve_default=False,
        ),
    ]
