# Generated by Django 4.2 on 2023-05-10 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_groups', '0004_rename_author_group_user_creator'),
        ('tasks', '0005_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_groups',
            field=models.ManyToManyField(blank=True, to='user_groups.group_user'),
        ),
    ]
