# Generated by Django 4.2 on 2023-05-10 12:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_groups', '0002_alter_group_user_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group_user',
            name='author',
            field=models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='created_group_user', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
