# Generated by Django 4.2 on 2023-05-10 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_groups', '0003_alter_group_user_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group_user',
            old_name='author',
            new_name='creator',
        ),
    ]
